CREATE OR REPLACE TASK STREAMING_DB.KAFKA.DELETE_OLD_EARTHQUAKES
    WAREHOUSE = STREAMING_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
    DELETE FROM STREAMING_DB.KAFKA.EARTHQUAKES
    WHERE RECEIVED_AT < DATEADD(DAY, -2, CURRENT_TIMESTAMP());

